select generate_series(now(), 'tomorrow', interval '1 hour');

create table wf (
	id integer primary key generated by default as identity,
	event_date date not null,
	amount numeric not null,
	owner text not null,
	notes text
);

insert into wf(event_date, amount, owner)
select '2000-01-01'::date + random(0, 110000), random(-1000, 1000), 'Boris'
from generate_series(1, 1000);
insert into wf (event_date, amount, owner) values ('2000-01-01', 2300, 'Alexander');

with t as (
select event_date, owner,
 coalesce(sum(amount) filter (where amount < 0)
	over( partition by owner order by event_date rows between unbounded preceding and current row), 0) as expenditure, --window function
 coalesce(sum(amount) filter (where amount > 0)
	over(partition by owner order by event_date rows between unbounded preceding and current row), 0) as earning
from wf )
select *, earning + expenditure as ballance 
from t
order by event_date;

create table delme1 (id integer primary key , t text[]);
insert into delme1 values
(1, '{one two three}'),
(2, '{eleven, twelve, thirteen}');

select * from delme1;